" Autoload .vimrc on save
augroup myvimrchooks
    au!
    autocmd bufwritepost .vim/vimrc source ~/.vim/vimrc
augroup END

" General Configuration
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=4
set clipboard=unnamed
set number
set hidden

set spelllang=en
set spellfile=$HOME/.vim/spellfile/en.utf-8.add
set spell 

augroup txtspell
  autocmd!
  autocmd FileType markdown,mkd setlocal spell
  autocmd FileType text         setlocal spell
  autocmd BufRead,BufNewFile *.md setlocal spell
  autocmd BufRead,BufNewFile .gitignore setlocal nospell
augroup END

nmap \s i<C-X><C-S>

nnoremap k gk
nnoremap j gj
nnoremap <F5> :UndotreeToggle<CR>

nnoremap <Up> gk
nnoremap <Down> gj

" remap clipboard yank
noremap ,y "+yy
noremap ,p "+p

" Installed Plugins
call plug#begin("~/.vim/bundle")

" Cosmetic
Plug 'morhetz/gruvbox'
Plug 'NLKNguyen/papercolor-theme'
Plug 'itchyny/lightline.vim'
Plug 'kshenoy/vim-signature'

" Autocomplete
Plug 'maralla/completor.vim'
Plug 'lvht/phpcd.vim', { 'for': 'php', 'do': 'composer install' }

" Syntax Coloring
Plug 'plasticboy/vim-markdown'

" IDE Tools
Plug 'w0rp/ale'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'godlygeek/tabular'
Plug 'maximbaz/lightline-ale'

" File Browsing
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'aufgang001/vim-nerdtree_plugin_open'

Plug 'iamcco/markdown-preview.vim'
Plug 'gisphm/vim-gitignore'
Plug 'tpope/vim-fugitive'

" Writing Tools
Plug 'reedes/vim-lexical'
Plug 'reedes/vim-wordy'
Plug 'reedes/vim-pencil'

" Navigation/Motion
Plug 'reedes/vim-wheel'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tmux-plugins/vim-tmux-focus-events'

" Misc Productivity
Plug 'dhruvasagar/vim-dotoo'
Plug 'roxma/vim-tmux-clipboard'
Plug 'chrisbra/vim-autosave'
Plug 'mbbill/undotree'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/goyo.vim'
Plug 'vim-scripts/Drawit'

call plug#end()

let g:nerdtree_plugin_open_cmd = '/usr/bin/xdg-open'

" Autocomplete Options
let g:completor_node_binary = "/usr/bin/node"

" Theme options
let g:gruvbox_italic = 1
let g:gruvbox_contrast_dark = "hard"

set background=dark
colorscheme gruvbox

"let g:PaperColor_Theme_Options = {
"  \   'theme': {
"  \     'default.dark': { 
"  \       'allow_bold' : 1,
"  \       'allow_italic' : 1
"  \     }
"  \   }
"  \ }



" Markdown Preview
nmap gm <Plug>MarkdownPreview

" Lightline config
let g:lightline = { 
  \   'colorscheme': 'gruvbox',
  \   'active': {
  \     'left': [ [ 'mode', 'paste' ],
  \             [ 'readonly', 'filename', 'modified', 'fugitive', 'pencil' ] ]
  \   },
  \   'component': { 
  \     'pencil': '%{PencilMode()}',
  \     'fugitive': '%{FugitiveStatusline()}'
  \   }
  \ }
let g:lightline.component_expand = {
  \  'linter_checking': 'lightline#ale#checking',
  \  'linter_warnings': 'lightline#ale#warnings',
  \  'linter_errors': 'lightline#ale#errors',
  \  'linter_ok': 'lightline#ale#ok',
  \ }

let g:lightline.component_type = {
  \     'linter_checking': 'left',
  \     'linter_warnings': 'warning',
  \     'linter_errors': 'error',
  \     'linter_ok': 'left',
  \ }

let g:lightline.active = { 'right': [[ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]] }

let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf071"
let g:lightline#ale#indicator_errors = "\uf05e"
let g:lightline#ale#indicator_ok = "\uf00c"

set laststatus=2

" Goyo
map go :Goyo<CR>

let g:goyo_width = '75%'
let g:goyo_height = '90%'

function! s:goyo_enter()
  silent !tmux set status off
  silent !tmux list-panes -F '\#F' | grep -q Z || tmux resize-pane -Z
  set showmode
  set noshowcmd
  set linebreak
  set scrolloff=999
endfunction

function! s:goyo_leave()
  silent !tmux set status on
  silent !tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z
  set noshowmode
  set showcmd
  set scrolloff=5
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

" Tabs
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <silent> <A-Left> :execute 'silent! tabmove ' . (tabpagenr()-2)<CR>
nnoremap <silent> <A-Right> :execute 'silent! tabmove ' . (tabpagenr()+1)<CR>

" NERDTree
map <F2> :NERDTreeToggle<CR>

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" Ctrlp
let g:ctrlp_cmd='CtrlP :pwd'

" ftplugin
filetype plugin on

" vim-markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_new_list_item_indent = 0

" Pencil
let g:pencil#mode_indicators = {'hard': '🖉␍', 'auto': '🖉ª', 'soft': '🖉⤸', 'off': '',}

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init()
augroup END

" Overrides
set conceallevel=3
hi clear SpellBad
hi SpellBad cterm=strikethrough
set wrap linebreak nolist

" autosave
let g:autosave_backup = "~/.vim/backup"

set undofile
set undodir=$HOME/.vim/undo

