# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployer.splitmedialabs.com/commit: efd1b3f07a86bdb7b75b0601b11d1ebb3f17bd1d
    deployer.splitmedialabs.com/deploy_time: Thu Nov 25 10:48:40 UTC 2021
    deployer.splitmedialabs.com/repository: XSW
    deployer.splitmedialabs.com/stage: production
    deployment.kubernetes.io/revision: "32"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployer.splitmedialabs.com/commit":"efd1b3f07a86bdb7b75b0601b11d1ebb3f17bd1d","deployer.splitmedialabs.com/deploy_time":"Thu Nov 25 10:48:40 UTC 2021","deployer.splitmedialabs.com/repository":"XSW","deployer.splitmedialabs.com/stage":"production"},"labels":{"type":"workers"},"name":"workers","namespace":"rev-master"},"spec":{"minReadySeconds":10,"replicas":1,"revisionHistoryLimit":1,"selector":{"matchLabels":{"type":"workers"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"ad.datadoghq.com/workers.check_names":"[\"prometheus\"]","ad.datadoghq.com/workers.init_configs":"[{}]","ad.datadoghq.com/workers.instances":"[{\"prometheus_url\":\"http://%%host%%:9847/metrics\",\"namespace\":\"workers\",\"metrics\":[\"*\"]}]","ad.datadoghq.com/workers.logs":"[{\"source\":\"node-workers\",\"service\":\"workers\"}]","checksum/config":"587faa7f2f61826c13ff18db6b324bbcb38c7b513ae7f7b1349b9843a0cc7cb0"},"labels":{"type":"workers"}},"spec":{"containers":[{"command":["node","src/index.js"],"env":[{"name":"ENVIRONMENT","value":"production"},{"name":"LOG_LEVEL","value":"silly"}],"image":"eu.gcr.io/xsplit-ops/services/workers:efd1b3f07a86bdb7b75b0601b11d1ebb3f17bd1d","name":"workers","resources":{"requests":{"cpu":"500m","memory":"1024Mi"}},"volumeMounts":[{"mountPath":"/srv/workers/.env","name":"workers-cfg","subPath":".env"},{"mountPath":"/srv/workers/gcloud_application.json","name":"workers-cfg","subPath":"gcloud_application.json"}]}],"nodeSelector":{"worker":"1"},"volumes":[{"configMap":{"name":"workers-cfg"},"name":"workers-cfg"}]}}}}
  creationTimestamp: "2021-09-09T08:02:11Z"
  generation: 63
  labels:
    type: workers
  name: workers
  namespace: rev-master
  resourceVersion: "62106802"
  selfLink: /apis/apps/v1/namespaces/rev-master/deployments/workers
  uid: f45390eb-2639-4979-b719-915db3e04c4e
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 20
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      type: workers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/workers.check_names: '["prometheus"]'
        ad.datadoghq.com/workers.init_configs: '[{}]'
        ad.datadoghq.com/workers.instances: '[{"prometheus_url":"http://%%host%%:9847/metrics","namespace":"workers","metrics":["*"]}]'
        ad.datadoghq.com/workers.logs: '[{"source":"node-workers","service":"workers"}]'
        checksum/config: 587faa7f2f61826c13ff18db6b324bbcb38c7b513ae7f7b1349b9843a0cc7cb0
      creationTimestamp: null
      labels:
        type: workers
    spec:
      containers:
      - command:
        - node
        - src/index.js
        env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: silly
        - name: FFMPEG_PATH
          value: "/srv/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
        - name: FFPROBE_PATH
          value: "/srv/node_modules/@ffprobe-installer/linux-x64/ffprobe"
        image: eu.gcr.io/xsplit-ops/services/workers:efd1b3f07a86bdb7b75b0601b11d1ebb3f17bd1d
        imagePullPolicy: IfNotPresent
        name: workers
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/workers/.env
          name: workers-cfg
          subPath: .env
        - mountPath: /srv/workers/gcloud_application.json
          name: workers-cfg
          subPath: gcloud_application.json
      dnsPolicy: ClusterFirst
      nodeSelector:
        worker: "1"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: workers-cfg
        name: workers-cfg
status:
  availableReplicas: 20
  conditions:
  - lastTransitionTime: "2021-11-25T10:49:49Z"
    lastUpdateTime: "2021-11-25T10:49:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-12T07:20:27Z"
    lastUpdateTime: "2021-11-25T10:50:57Z"
    message: ReplicaSet "workers-5949c88999" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 63
  readyReplicas: 20
  replicas: 20
  updatedReplicas: 20
